  esignet:
    image: 'mosipid/esignet-with-plugins:1.5.1'
    user: root
    ports: 
      - 8088:8088
    environment:
      - container_user=mosip
      - active_profile_env=default,local
      - plugin_name_env=esignet-mock-plugin.jar
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mosip_esignet?currentSchema=esignet
      - MOSIP_ESIGNET_MOCK_DOMAIN_URL=http://mock-identity-system:8082
      - MOSIP_ESIGNET_INTEGRATION_KEY_BINDER=MockKeyBindingWrapperService
      - SPRING_CACHE_TYPE=redis
      - SPRING_REDIS_HOST=redis-server
      - SPRING_REDIS_PASSWORD=
      - MOSIP_ESIGNET_HOST=http://34.35.69.91:8088
      - MOSIP_ESIGNET_DISCOVERY_ISSUER_ID=http://34.35.69.91:8088
      - MOSIP_ESIGNET_TOKEN_ENDPOINT=http://34.35.69.91:8088/oauth/token
    depends_on:
      - database
      - mock-identity-system
      - redis
